### PR TITLE
Support for DNS challenge

### PR DESCRIPTION
**Pull request by daweedm**
Hello @buchdag 
I have added the support for DNS challenges, as it's supported by acme.sh and with minor changes to the `acme-companion` code base.

Could you review this pull request ?

### CODE REVIEW

**Comment by daweedm** [comment]
Forgot to mention that this PR is not specific to any provider, as the idea is to "forward" required environment variables by each provider and which are defined in the proxied container, to the letsencrypt_service. Then, these variables are simply read by acme.sh.

**Comment by mustanggb** [comment]
Why are you doing this:
```
if [[ -z "$variable" ]]; then
  <do nothing>
else
  < do something>
fi
```

Instead of this:
```
if [[ -n "$variable" ]]; then
  < do something>
fi
```

I imagine some HTTP challenge stuff should not happen for a DNS challenge.
Perhaps this is a good place to start:
```
add_location_configuration "$domain" || reload_nginx
```

**Review by mustanggb — CHANGES_REQUESTED** [review]
Why are you doing this:
```
if [[ -z "$variable" ]]; then
  <do nothing>
else
  <do something>
fi
```

Instead of this:
```
if [[ -n "$variable" ]]; then
  <do something>
fi
```

I imagine some HTTP challenge stuff should not happen for a DNS challenge.
Perhaps this is a good place to start:
```
add_location_configuration "$domain" || reload_nginx
```

**Comment by ne0YT** [comment]
I would love to see this happening in the official image.. I want to integrate it in some "offline" setups. where devices have internet and are random/not managed, but the services are not publicly available.

**Comment by zorbathut** [comment]
For what it's worth, I am now using this locally and it seems to be working. I do wish there was a better way to handle all the variables; I end up with the same block of variables copypasted multiple places in order to handle various subdomains. On the other hand, this is relevant only for people running multiple subdomains, and I'm not sure how common that is.

**Comment by zorbathut** [comment]
Alright, never mind, update :V

It works fine on single domains but I'm having trouble getting it working on multidomains; it does the first domain with DNS, but then seems to fall back on HTTP for the second domain.

Somewhat-anonymized log:

```
[Wed Jun 28 01:35:42 UTC 2023] Multi domain='DNS:www.[mydomain].com,DNS:[mydomain].com'
[Wed Jun 28 01:35:42 UTC 2023] Getting domain auth token for each domain
[Wed Jun 28 01:35:43 UTC 2023] Getting webroot for domain='www.[mydomain].com'
[Wed Jun 28 01:35:44 UTC 2023] Getting webroot for domain='[mydomain].com'
[Wed Jun 28 01:35:44 UTC 2023] www.[mydomain].com is already verified, skip dns-01.
[Wed Jun 28 01:35:44 UTC 2023] Verifying: [mydomain].com
[Wed Jun 28 01:35:46 UTC 2023] Pending
[Wed Jun 28 01:35:48 UTC 2023] Pending
[Wed Jun 28 01:35:51 UTC 2023] Pending
[Wed Jun 28 01:35:53 UTC 2023] Pending
[Wed Jun 28 01:35:55 UTC 2023] [mydomain].com:Verify error:1.2.3.4: Fetching http://[mydomain].com/.well-known/acme-challenge/[challenge-string]: Timeout during connect (likely firewall problem)
[Wed Jun 28 01:35:55 UTC 2023] Please check log file for more details: /dev/null
```

Not sure what I'm doing wrong.

**Comment by daweedm** [comment]
> For what it's worth, I am now using this locally and it seems to be working. I do wish there was a better way to handle all the variables; I end up with the same block of variables copypasted multiple places in order to handle various subdomains. On the other hand, this is relevant only for people running multiple subdomains, and I'm not sure how common that is.

If you are using docker-compose, you can store your common environment variables in a file, e.g. `mydnsprovider.env`, and reference it in multiple containers like this :
```yaml
version: '3'
services:
  first:
    image: nginx
    env_file:
      - path/to/mydnsprovider.env
    environment:
      - VIRTUAL_HOST=first.com
      - LETSENCRYPT_HOST=first.com
```

and

```yaml
version: '3'
services:
  second:
    image: nginx
    env_file:
      - path/to/mydnsprovider.env
    environment:
      - VIRTUAL_HOST=second.com
      - LETSENCRYPT_HOST=second.com
```

https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-env_file-attribute

**Comment by daweedm** [comment]
> Alright, never mind, update :V
> 
> It works fine on single domains but I'm having trouble getting it working on multidomains; it does the first domain with DNS, but then seems to fall back on HTTP for the second domain.
> 
> Somewhat-anonymized log:
> 
> ```
> [Wed Jun 28 01:35:42 UTC 2023] Multi domain='DNS:www.[mydomain].com,DNS:[mydomain].com'
> [Wed Jun 28 01:35:42 UTC 2023] Getting domain auth token for each domain
> [Wed Jun 28 01:35:43 UTC 2023] Getting webroot for domain='www.[mydomain].com'
> [Wed Jun 28 01:35:44 UTC 2023] Getting webroot for domain='[mydomain].com'
> [Wed Jun 28 01:35:44 UTC 2023] www.[mydomain].com is already verified, skip dns-01.
> [Wed Jun 28 01:35:44 UTC 2023] Verifying: [mydomain].com
> [Wed Jun 28 01:35:46 UTC 2023] Pending
> [Wed Jun 28 01:35:48 UTC 2023] Pending
> [Wed Jun 28 01:35:51 UTC 2023] Pending
> [Wed Jun 28 01:35:53 UTC 2023] Pending
> [Wed Jun 28 01:35:55 UTC 2023] [mydomain].com:Verify error:1.2.3.4: Fetching http://[mydomain].com/.well-known/acme-challenge/[challenge-string]: Timeout during connect (likely firewall problem)
> [Wed Jun 28 01:35:55 UTC 2023] Please check log file for more details: /dev/null
> ```
> 
> Not sure what I'm doing wrong.

Passing multiple domains is done the same way by using multiple `-d` flags, either using web or dns challenge according to https://github.com/acmesh-official/acme.sh#9-use-dns-manual-mode so it should work as is since I didn't modified the behaviour related to the `-d` flag in this PR. How does your config looks like ?

**Comment by yeliex** [comment]
@mustanggb any progress please?

**Comment by mustanggb** [comment]
Nothing to do with me.

1. @daweedm hasn't made the requested changes.
2. I don't have commit access.

**Comment by cistes44** [comment]
Hello @buchdag, any plan on this? If none, please let me know, I could take over the commit, try to fix things @mustanggb pointed out.

**Comment by daweedm** [comment]
@mustanggb @yeliex  @cistes44 sorry guys, I hadn't a lot of spare time last weeks. I'll try to take care of it if I can find some time soon. Meanwhile, feel free to pursue the work, there is not much left. @mustanggb what exactly do you need me to do for you to get commit access?

**Review by sokai — APPROVED** [review]
Hey @buchdag, may I ask you please to merge this (= the *main* feature: DNS challenge with *single domain*) in an official release (and solve the *multi-domain* thing later)?

Review:
* feature is/seems very needed
* single domain seems to work
* multi-domain not working (can be done later)

#ty! @daweedm

Thanks a lot in advance + KR

**Comment by cxhamilton** [comment]
+1 for this feature for the same reason as other comments left in this thread

**Comment by buchdag** [comment]
This PR will be completed in #1137.

**Pull request closed without merging**
